"""Reads and writes a diagram as YAML or JSON.

A specification describes the same thing the Python API builds, so a diagram
can be written by hand, generated by another program, or checked into a
repository beside the paper it illustrates.

The layer types are found by walking :class:`~synaplot.core.base.Layer`, so a
layer you define yourself can be used in a specification as soon as it is
imported, with no registration step.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import TYPE_CHECKING, Any

import yaml
from pydantic import TypeAdapter

from synaplot.core.base import Layer
from synaplot.core.diagram import Diagram

if TYPE_CHECKING:
    from collections.abc import Iterator

__all__ = ["dump", "dumps", "layer_types", "load", "loads", "schema"]


def _descendants(base: type[Layer]) -> Iterator[type[Layer]]:
    """Yield every class below a base, however deeply nested."""
    for subclass in base.__subclasses__():
        yield subclass
        yield from _descendants(subclass)


def layer_types() -> dict[str, type[Layer]]:
    """Return the layers a specification can name.

    A layer counts once it declares a ``kind`` field. The bases that layers
    share, such as ``BoxLayer``, have no ``kind`` and are left out.

    Returns
    -------
    dict of str to type of Layer
        Each ``kind`` and the class that draws it.

    Examples
    --------
    >>> kinds = layer_types()
    >>> kinds["conv"].__name__, kinds["dense"].__name__
    ('Conv', 'Dense')
    """
    found: dict[str, type[Layer]] = {}
    # mypy treats an abstract class as unusable where a type is expected, but
    # walking the hierarchy is exactly the point here.
    for subclass in _descendants(Layer):  # type: ignore[type-abstract]
        field = subclass.model_fields.get("kind")
        if field is not None and isinstance(field.default, str):
            found[field.default] = subclass
    return dict(sorted(found.items()))


def _to_layer(value: Any) -> Layer:
    """Return the layer a mapping describes.

    Parameters
    ----------
    value
        A mapping with a ``kind``, or a layer that is already built.

    Raises
    ------
    ValueError
        If ``kind`` is missing or names no known layer.
    """
    if isinstance(value, Layer):
        return value
    if not isinstance(value, dict):
        raise TypeError(f"a layer must be a mapping, not {type(value).__name__}")
    known = layer_types()
    kind = value.get("kind")
    if kind is None:
        raise ValueError(f"a layer needs a kind; choose one of {', '.join(known)}")
    if kind not in known:
        raise ValueError(
            f"unknown layer kind {kind!r}; choose one of {', '.join(known)}"
        )
    return known[kind].model_validate({k: v for k, v in value.items() if k != "kind"})


def loads(text: str) -> Diagram:
    """Return the diagram a YAML or JSON document describes.

    JSON is valid YAML, so both are read the same way.

    Parameters
    ----------
    text
        The document to read.

    Returns
    -------
    Diagram
        The diagram it describes.

    Raises
    ------
    ValueError
        If the document is not a mapping, or names a layer that does not exist.

    Examples
    --------
    >>> diagram = loads('''
    ... name: tiny
    ... layers:
    ...   - {kind: conv, name: conv1, filters: 64, spatial: 224}
    ...   - {kind: pool, name: pool1}
    ... connections:
    ...   - {source: conv1, target: pool1}
    ... ''')
    >>> diagram.name, [layer.name for layer in diagram.layers]
    ('tiny', ['conv1', 'pool1'])

    A kind that does not exist says what the choices are:

    >>> loads("layers: [{kind: attention, name: a}]")
    Traceback (most recent call last):
        ...
    ValueError: unknown layer kind 'attention'; choose one of ...
    """
    document = yaml.safe_load(text)
    if not isinstance(document, dict):
        raise ValueError("a specification must be a mapping of settings")
    fields = dict(document)
    fields["layers"] = [_to_layer(item) for item in fields.get("layers") or []]
    return Diagram.model_validate(fields)


def load(path: str | Path) -> Diagram:
    """Return the diagram a YAML or JSON file describes.

    Parameters
    ----------
    path
        The file to read.

    Returns
    -------
    Diagram
        The diagram it describes.
    """
    return loads(Path(path).read_text(encoding="utf-8"))


def dumps(diagram: Diagram, *, as_json: bool = False) -> str:
    """Return a diagram as a YAML or JSON document.

    Parameters
    ----------
    diagram
        The diagram to write.
    as_json
        Whether to write JSON instead of YAML.

    Returns
    -------
    str
        A document that :func:`loads` reads back into an equal diagram.
    """
    data = diagram.model_dump(mode="json", exclude_defaults=True)
    data["layers"] = [
        {"kind": type(layer).model_fields["kind"].default, **item}
        for layer, item in zip(diagram.layers, data.get("layers", []), strict=True)
    ]
    if as_json:
        return json.dumps(data, indent=2) + "\n"
    return yaml.safe_dump(data, sort_keys=False, default_flow_style=False)


def dump(diagram: Diagram, path: str | Path) -> Path:
    """Write a diagram to a YAML or JSON file.

    The format comes from the file's suffix.

    Parameters
    ----------
    diagram
        The diagram to write.
    path
        Where to write it.

    Returns
    -------
    Path
        The file that was written.
    """
    target = Path(path)
    as_json = target.suffix.lower() == ".json"
    target.write_text(dumps(diagram, as_json=as_json), encoding="utf-8")
    return target


def schema() -> dict[str, Any]:
    """Return a JSON Schema describing a specification.

    The schema lists every layer kind and the settings it takes, so an editor
    can complete a specification and a program can check one before running it.

    Returns
    -------
    dict
        A JSON Schema document.
    """
    document = TypeAdapter(Diagram).json_schema(
        ref_template="#/$defs/{model}",
        mode="validation",
    )
    definitions = document.setdefault("$defs", {})
    variants = []
    for kind, layer in layer_types().items():
        name = layer.__name__
        definitions[name] = _layer_schema(kind, layer, definitions)
        variants.append({"$ref": f"#/$defs/{name}"})
    document.setdefault("properties", {})["layers"] = {
        "type": "array",
        "items": {"oneOf": variants, "discriminator": {"propertyName": "kind"}},
        "description": "The layers to draw, in drawing order.",
    }
    document["title"] = "synaplot diagram"
    document["$schema"] = "https://json-schema.org/draft/2020-12/schema"
    return document


def _layer_schema(
    kind: str, layer: type[Layer], definitions: dict[str, Any]
) -> dict[str, Any]:
    """Return the schema for one layer kind, with its ``kind`` pinned.

    Anything the layer refers to, such as its size, is moved into the shared
    definitions so every reference in the finished schema resolves.
    """
    document = layer.model_json_schema(ref_template="#/$defs/{model}")
    definitions.update(document.pop("$defs", {}))
    document.setdefault("properties", {})["kind"] = {"const": kind, "type": "string"}
    required = document.setdefault("required", [])
    if "kind" not in required:
        required.append("kind")
    return document
